baseURL = 'https://ashikahmad.github.io/timely/'
languageCode = 'en-us'
title = 'Timely'
theme = "Portio"

[params]
footerLogo = "images/icon_64.png"
footerLogoLabel = "Timely"
logo = "images/icon_64.png"
copyright = "All right reserved copyright © BlessedPixels.com 2020"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Features"
url = "#features"
weight = 3
[[menu.main]]
name = "FAQ"
url = "#faq"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3

[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "hello@example.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"
